-- function _G.ReloadConfig()
--     for name, _ in pairs(package.loaded) do
--         if name:match("^jaron") and not name:match("nvim-tree") then
--             package.loaded[name] = nil
--         end
--     end
--
--     dofile(vim.fn.stdpath("config") .. "/init.lua")
--     vim.notify("Reloaded config!", vim.log.levels.INFO)
-- end
--
-- vim.api.nvim_set_keymap("n", "<leader>rr", "<cmd>lua ReloadConfig()<CR>", {noremap = true, silent = true})
