-- return {
--   { "Exafunction/codeium.vim", enabled = false },
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "hrsh7th/nvim-cmp",
--   },
--   config = function()
--     require("codeium").setup({})
--   end,
-- }
--
return {}
